.build_docker_template:
  only:
    - pushes
    - merge_requests
  tags:
    - docker-privileged
  image: docker:19.03.1
  services:
  # To obtain a Docker daemon, request a Docker-in-Docker service
  - docker:19.03.1-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY
    # Need to start the automounter for CVMFS:
    # - docker run -d --name cvmfs --pid=host --user 0 --privileged --restart always -v /shared-mounts:/cvmfsmounts:rshared gitlab-registry.cern.ch/vcs/cvmfs-automounter:master
  script:
    # ls /cvmfs/cms.cern.ch/ won't work, but from the container it will
    # If you want to automount CVMFS on a new docker container add the volume config /shared-mounts/cvmfs:/cvmfs:rslave
    - docker run  -v $(pwd):$(pwd) -w $(pwd) --name ${CI_PROJECT_NAME} ${FROM} /bin/bash ./.gitlab/setup_docker.sh ${CLUSTER}
    - SHA256=$(docker commit ${CI_PROJECT_NAME})
    - docker tag ${SHA256} ${TO}
    - docker push ${TO}


#--------------------------------------------------------------------
build_docker_infn_facility:
  extends: .build_docker_template
  variables:
    FROM: dciangot/jlab-rclone:v7
    TO: ${CI_REGISTRY_IMAGE}:infn-latest
    CLUSTER: "INFN"

build_docker_lxplus:
  extends: .build_docker_template
  variables:
    FROM: batch-team/dask-lxplus/lxdask-c8:latest
    TO: ${CI_REGISTRY_IMAGE}:lxplus-latest
    CLUSTER: "lxplus"

#-------------------------------------------------------------------

build_docker_infn_facility_tagged:
  extends: build_docker_infn_facility
  only:
    - tags
  variables:
    TO: ${CI_REGISTRY_IMAGE}:infn-${CI_COMMIT_TAG}
    
build_docker_lxplus_tagged:
  extends: build_docker_lxplus
  only:
    - tags
  variables:
    TO: ${CI_REGISTRY_IMAGE}:lxplus-${CI_COMMIT_TAG}
